### ISSUE TITLE
Wunsch :: Ersetzen des Standard-Upload-Dialoges

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/multiupload#1]
Aus meiner Sicht würde es Sinn machen den Standard-Dialog für den Upload zu ersetzen, wenn multiupload installiert ist. Das erspart einiges an Support beim DAU.

**Comment by darwin26** [comment]
Welchen würdest du vorschlagen?

**Comment by skerbis** [comment]
Welchen? Die Frage verstehe ich nicht. Der normale Upload-Reiter im Medienpool sollte halt verschwinden, wenn Multiupload installiert ist.

**Comment by darwin26** [comment]
ah.. jetzt hats geklingelt. ok. macht sinn...
werd das die tage mal testen...

**Comment by darwin26** [comment]
HI. PR wäre schon raus. Kannst du das bitte mal testen ...
oder hier: https://github.com/darwin26/multiupload

**Comment by skerbis** [comment]
https://github.com/darwin26/multiupload 
Habe ich getestet, was hat sich geändert? Sehe nichts

**Comment by skerbis** [comment]
Mist! Warscheinlich den falschen Branch benutzt. 
Die Metaangaben haben keine Funktion - korrekt?
![bildschirmfoto 2016-12-21 um 17 07 37](https://cloud.githubusercontent.com/assets/791247/21396289/fd892892-c79f-11e6-80b9-95b5e4a38298.png)

**Comment by darwin26** [comment]
HI,
eigentlich sollte es nun so aussehen:
![screen20161222_medienpool_dev](https://cloud.githubusercontent.com/assets/189407/21421913/8dbd05c4-c835-11e6-8f24-595068cdd486.png)

**Comment by darwin26** [comment]
ich check das mal ...

**Comment by skerbis** [comment]
Ich habe dieses Build getestet: https://github.com/darwin26/multiupload/tree/update-darwin
Oder habe ich was falsch gemacht?

**Comment by darwin26** [comment]
hi. @skerbis ... hast du die aktuelle version schon getestet?

**Comment by skerbis** [comment]
hi, ich habe gerade die aktuelle Version aus Github geladen. Sieht immer noch so aus, dass die Metaangaben abgefragt werden. 
![bildschirmfoto 2017-02-05 um 16 13 38](https://cloud.githubusercontent.com/assets/791247/22627200/5b635f7c-ebbe-11e6-925f-537b4a9985c2.png)

**Comment by darwin26** [comment]
ok. danke. zumindest sollte der MP nun aufgeräumter wirken... also nur noch multiupload. wird datei sync eigentlich gebraucht?

**Comment by skerbis** [comment]
Datei Sync evtl. optional, da Dateien auch auf anderen Weg in den Medienpool gelangen können, z.B. durch andere Websites
