### ISSUE TITLE
Nicht mehr im Installer zu finden

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/multiupload#11]

**Comment by hirbod** [comment]
Ich muss noch warten, bis @darwin26 den alten Eintrag auf Redaxo.org löscht, damit ich die neue Version pflegen kann

**Comment by tbaddade** [comment]
Inwiefern musst du warten? Du könntest einfach die Version via Installer aus dem Backend heraus hochladen.

**Comment by hirbod** [comment]
Ich hab keinen Key etc. Die Redaxo5 Version ist mit @darwin26 Account verbunden. Der kommt aber erst am Montag dazu. Falls Zugriff darauf hast, kannst du natürlich auch gerne seinen Eintrag löschen, dann registriere ich den Key sofort.

**Comment by hirbod** [comment]
Ich habe nur Zugriff auf den key "rex_multiupload" (Version REX4). Ich brauch aber "multiupload"

**Comment by tbaddade** [comment]
> Die Redaxo5 Version ist mit @darwin26 Account verbunden

Das stimmt so nicht. Der Key `multiupload` ist mit dem FOR-Account verbunden. Du bräuchtest im Installer nur die FOR-Api-Daten hintelegen und könntest dann das AddOn bereitstellen.

PS: Jedes AddOn bei FOR ist mit dem FOR-Account verbunden.
PPS: Die Api-Daten erhält man im Slack-Channel.

**Comment by hirbod** [comment]
Ok, ich habe dazu keine Daten.

**Comment by Hirbod** [comment]
magst mir die an info@nightstomp.com schicken?

**Comment by tbaddade** [comment]
@Hirbod siehe Slack

**Comment by hirbod** [comment]
fixed
