### ISSUE TITLE
Benutzerrechte

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/multiupload#12]
Hallo, 

wenn ich das AddOn Multiupload installiere und einem Benutzer aber nicht die Rechte gebe dieses zu verwenden erscheint dann leider aber nicht mehr das "normale" Media-Einzel-Upload !

Anderer Wunsch: Es wäre schön wenn ich dem Benutzer die Multiupload-Rechte gebe das dann, automatisch wie gehabt, das Einzel-Upload-Fenster ersetzt wird durch das Multi-Upload_Fenster aber ohne dem Eintrag unter AddOns in der linken Spalte unter dem Hauptmenü.

**Comment by hirbod** [comment]
Danke, werde ich mir anschauen. Das Ausblenden aus der linken Spalte könnte man ggf. als Config mit anbieten, und zur Laufzeit dann entfernen. Ich würde hierzu aber noch die Meinung der anderen abwarten wollen.

**Comment by hirbod** [comment]
fixed
