### ISSUE TITLE
Synchronisieren Tab fehlt

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/multiupload#13]

**Comment by hirbod** [comment]
Das wurde hier von den Jungs wohl beabsichtigt entfernt. Ich sehe das auch eher als Einstellungssache. Ich werde es als Setting in einer Settingspage aufnehmen

**Comment by darwin26** [comment]
das war mehr oder weniger n test wie man tabs in addons ausblendet. sollte wieder hinzugefügt/eingeblendet werden @hirbod

danke
