### ISSUE TITLE
MetaInfo-Felder sind beim Upload nicht vorhanden

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/multiupload#14]

**Comment by hirbod** [comment]
Ein relativ problematisches Thema bei einem Multiupload. Soll es aber in der nächsten, großen Version geben.

**Comment by skerbis** [comment]
Bei mir werden Meta-Infos , jedoch ohne Funktion, angezeigt
![bildschirmfoto 2017-03-20 um 12 48 10](https://cloud.githubusercontent.com/assets/791247/24098580/7ef92a4c-0d6b-11e7-8003-830cb9d328e2.png)

**Comment by hirbod** [comment]
Ja, sind ohne Funktion, bin dran.

**Comment by hirbod** [comment]
Und Titel fehlt.

**Comment by skerbis** [comment]
Ich würde es weglassen. Die Metas sollten nach dem Upload bearbeitet werden. Ein Hinweis dazu würde reichen. Natürlich gibt es evtl. das eine oder andere Metafeld, das interessant sein könnte, z.B. Quellangaben (pixelio, getty und andere Abmahner), aber das ist ja kein Default-Meta

**Comment by hirbod** [comment]
Meta-Infos werden sau häufig angefragt. Ich werd es einbauen. Gerade so Copyright geschichten wollen die User am liebsten in einem Wusch abgearbeitet haben

**Comment by skerbis** [comment]
Aber eine Default-Beschreibung, Titel etc? ... erschließt sich mir nicht. Zur schnellen Nachbearbeitung großer Uploads könnte eine History noch helfen.

**Comment by hirbod** [comment]
Ich werde die Redaxo-Defaults übernehmen. Das sind Titel und eben die Metadaten. Muss ja nicht befüllt werden. Da ich aber z.B. nie den Default-Upload nutze, fehlt der Titel einfach.

**Comment by hirbod** [comment]
Was du nicht vergessen darfst: In meiner R4 Version war das einstellbar. Die Settingspage für den Multiupload fehlt noch, da kannst du dir dann die Meta-Infos auch deaktivieren.

**Comment by skerbis** [comment]
Was hälst du von einer History? Gerade nach großen Uploads. In R4 konnte man die Uploads nachträglich bearbeiten, aber man musste es sofort tun. Eine (längere) History in einem Reiter könnte helfen alle nacheinander zu bearbeiten. Halt ne längere Liste als in Quick Navigation

**Comment by hirbod** [comment]
Kann man als Feature besprechen. Ich könnte die Last-Files in eine Session schreiben, oder ein Plugin, das die History anhand des Zeitstempels lädt

**Comment by hirbod** [comment]
batch_edit / Stapelverarbeitung

**Comment by skerbis** [comment]
@Hirbod für die History ... einfach mein Fragment missbrauchen ;-) https://github.com/FriendsOfREDAXO/quick_navigation/blob/master/fragments/quick_articles.php
