### ISSUE TITLE
aktiver Zustand des Tabs ist beim hinzufügen/upload nicht erkennbar

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/multiupload#15]

**Comment by hirbod** [comment]
Verstehe das Ticket leider nicht so richtig. Bitte kurz erläutern.

**Comment by tbaddade** [comment]
Habe den Titel angepasst.

**Comment by hirbod** [comment]
Verstehe ich immer noch nicht. Bei mir ist es erkennbar. Bitte Screenshot
