### ISSUE TITLE
package.yml und weitere Dateien :: author richtig benennen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/multiupload#18]
Die Angabe des Authors entspricht nicht dem FOR-Standard. So soll es sein:
`author: Friends Of REDAXO`

Siehe dazu https://friendsofredaxo.github.io/info#ein-addon-zu-den-friends-of-redaxo-übertragen (Punkt 2). Wir machen das deshalb, damit alle FOR-AddOns einheitlich markiert sind, vor allem im Installer.

**Comment by hirbod** [comment]
Ok

**Comment by hirbod** [comment]
Ist doch schon der Fall?

**Comment by tbaddade** [comment]
Ist es nicht
https://github.com/FriendsOfREDAXO/multiupload/blob/master/plugins/upload_precompressor/package.yml

**Comment by hirbod** [comment]
Das Plugin hab ich mir gar nicht angeschaut

**Comment by hirbod** [comment]
fixed
