### ISSUE TITLE
Addon umbenennen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/multiupload#2]
FOR hatte sich darauf geeinigt, keine unnötigen Prefixe im Addon-Namen zu verwenden. Hier sollten wir deshalb den `rex5_`-Prefix entfernen.

Der Addon-Key `multiupload` ist allerdings schon belegt. Jedoch wurde das zugehörige Addon zuletzt 2011 geupdatet, so dass wir davon ausgehen, den Key übernehmen zu können. @joachimdoerr hat den Autor angefragt.

Falls jemand gegen `multiupload` ist, ist das übliche Prozedere: Hand heben :)

**Comment by schuer** [comment]
@joachimdoerr Gibt es schon Rückmeldung vom Autor des Addon-Keys?

**Comment by schuer** [comment]
Im Slack besprochen: Joachim hat leider keine Rückmeldung erhalten. Keine Reaktion vom Autor, und das Addon wurde vor 6 Jahren zuletzt angefasst: Wir waren neulich im Slack der Meinung, dass wir den Addon-Key deshalb bedenkenlos zu FOR übertragen können.

@tbaddade Könntest du das übernehmen? Gregor ist ja in den nächsten Wochen nicht verfügbar.

**Comment by tbaddade** [comment]
> Könntest du das übernehmen?

Addonkey ist nun :for: zugewiesen und die Umbenennung kann starten.

**Comment by schuer** [comment]
Erledigt.

Der letzte Stand des _alten_ Addons liegt im Branch `rex5_multiupload`. Ich habe die README um die Update-Info ergänzt und die package.yml für ein finales Release **1.1.0** vorbereitet. Dieses kann veröffentlicht werden, sobald wir am Ende der Challenge eine neue Major-Version fertig und veröffentlicht haben.

Der `master`-Branch ist für die neue Version **2.0.0** vorbereitet und der Addon-Key wurde entsprechend ersetzt.
