### ISSUE TITLE
Funktionslose Meta Infos im Upload-Formular

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/multiupload#21]
Durch diesen EP https://github.com/FriendsOfREDAXO/multiupload/blob/master/lib/upload.class.php#L226   werden Meta Infos in das Formular eingefügt. Allerdings sind sie für den Upload ohne Funktion und haben stets die Höhe des Ausgabefensters, wodurch das Uploadfeld immer erst durch scrollen sichtbar wird.

**Comment by hirbod** [comment]
Na vielen Dank für die Meldung. Ich hab das tatsächlich nach dem Port nie getestet und war froh, dass das "eingebaut" wurde.. Haha..

**Comment by hirbod** [comment]
Ich werde mir mal anschauen, wie der Medienpool das löst, es werden höchstwahrscheinlich einfach nur Parameter (dynamisch) abgefangen werden müssen. Ich stelle mir das nicht so dramatisch vor.

**Comment by hirbod** [comment]
#14

**Comment by hirbod** [comment]
Support für Metadaten gibt es in der nächsten großen Version, vorerst werde ich die Metadaten jedoch ausblenden

**Comment by hirbod** [comment]
vorerst fixed in 2.1.3
