### ISSUE TITLE
Multiupload 3.0

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/multiupload#23]
- [ ] Port nach FineUploader
- [ ] JS Preupload Resize mit Canvas
- [ ] Metadaten und Titel
- [ ] History mit Stapelverarbeitung
- [ ] Settingspage
- [ ] Droplet Widget im Header (ersetzt Quick-Upload)

**Comment by hirbod** [comment]
#22 #16 #14

**Comment by ghost** [comment]
Kennst du schon https://github.com/blueimp/jQuery-File-Upload? Hat 20.000 Sternchen mehr wie der FineUploader.

**Comment by hirbod** [comment]
Der FineUploader wird von ner großen Firma gesponsered, welche bezahlt an dem Projekt arbeiten. Es erscheint mir irgendwie sinnvoller, diese Lib zu nutzen. jQuery File Upload hat sogar die Issues deaktiviert, das ist Bugverschleierung..

**Comment by ghost** [comment]
> Bugverschleierung

da meint der autor aber was anderes: https://github.com/blueimp/jQuery-File-Upload/pull/3475#issuecomment-282288390

egal wollt nur drauf hinweisen.

**Comment by hirbod** [comment]
Ok, danke. Ich überlege es mir nach genauer Featureüberprüfung, welche Lib ich nutze. Beide machen einen sehr soliden Eindruck. Der FineUpload basiert halt auf dem Uploader, der im MUP 2.0 schon enthalten ist. ("valums uploader")

Da ich so zufrieden war, wollt ich gerade dabei bleiben. Aber eine Lib mit großer Community ist natürlich auch nicht verkehrt!

**Comment by skerbis** [comment]
Dann schmeiß ich denn hier auch noch rein in die Runde, https://github.com/kartik-v/bootstrap-fileinput/ - fineuploader gefällt mir aber auch

**Comment by ghost** [comment]
@Hirbod Und ich dachte mir dass 20.000+ User schon wissen warum sie aufs Star-Knöpfchen gedrückt haben (ausser es war ein Bot oder so ;))

**Comment by hirbod** [comment]
Masse != Klasse :)

Ich lass den Code und die Features entscheiden. Ich habs auf der Liste!

**Comment by schuer** [comment]
Gerne auch FOR-like zusammen entscheiden :)

**Comment by hirbod** [comment]
Ich dachte FOR unterliegt dem Präsidialsystem? Die Meinung des Parlaments zählt, aber am Ende entscheidet eh der Diktator der es entwickelt ;)

**Comment by schuer** [comment]
FOR hat ja keine in Stein gemeißelten Regeln, aber grundsätzlich geht es darum, gemeinsam an Projekten zu arbeiten. Nicht nur zwecks Abstimmung, sondern auch wegen Aufgabenteilung, (Qualitäts-)Kontrolle und Motivation. Fühlt sich halt schöner an, wenn man aktiv an einem Projekt mitgearbeitet hat, als wenn man es nur »vorgesetzt« bekommt. Und auch wenn die gemeinsame Abstimmung am Anfang der Entwicklung manchmal mühsam scheint — viele Köche verderben den Brei? —, zahlt es sich am Ende hoffentlich für das Projekt aus, indem es mehr oder besseren Input bekommen hat, als wenn nur eine Person dran gearbeitet hätte.

Es zählt also nicht nur die Meinung des Parlaments, wie du sagst, sondern es geht vielmehr darum, das Parlament zu motivieren und ihm möglichst viel Potential zu entlocken! Man könnte fast sagen: Es geht darum, das Projekt oder die Idee, die man vertritt, gegenüber dem Parlament zu bewerben und die Leute so sehr einzubeziehen, dass sie Teil des Projekts werden.

Manchmal allerdings, wenn das Parlament zu träge ist oder andere Themen bearbeitet, muss man auch einfach mal vorlaufen und Dinge alleine anstoßen, damit das Projekt nach vorne geht. Ist nicht immer leicht einzuschätzen. Aber ich glaube, FOR kriegt das nach und nach immer besser hin.
— Und du hast ja nun schon sehr viele FOR-Projekte in kürzester Zeit alleine angestoßen, was große Klasse ist! 👍

**Comment by hirbod** [comment]
Ich hab auch eher nen Witz gemacht ;)

**Comment by schuer** [comment]
Das war aber so eine schöne Vorlage, sowas mal allgemein anzubringen ;)

**Comment by tbaddade** [comment]
Gibt es einen etwaiges Releasedate für die 3.0 Version, welches bereits den FineUploader und das Scaling beinhaltet?

**Comment by hirbod** [comment]
Ich peile "irgendwann im Mai" an. Ich hab schon einiges lokal umgesetzt, ist aber noch lange nicht fertig.

**Comment by tbaddade** [comment]
Danke für die Info.

**Comment by hirbod** [comment]
Falls ich etwas Freizeit hab ggf. schon vorher.
