### ISSUE TITLE
Precompressor: normaler Single-File-Upload verursacht schwarze Bereiche

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/multiupload#28]
Wenn man den Precompressor aktiviert und ein Bild über die standard Einzel-Upload-Maske hochlädt, wird das Bild zwar auf 2500 Pixel Kantelänge verkleinert, aber es wird rechts und unter dem Bild schwarz hinzugefügt, siehe http://immocall.ch/media/immobilienmakler-zug-luzern-seesicht_2.jpg.

Wenn man dasselbe Bild mit dem Multiuploader hochlädt, geschieht dieser Fehler nicht. Wenn man den Precompressor deaktiviert, funktioniert es ebenfalls mit beiden Upload-Varianten.

Edit: ausserdem, bei diesem Beispiel ist das Ursprungsbild 3264 × 2448 gross mit ca. 2.3 MB. Wenn es per Precompress auf 2500 verkleinert wird (und trotz grossen schwarzen Bereichen), ist das Bild dann 3.1 MB gross. Macht nicht viel Sinn :)

**Comment by hirbod** [comment]
Das Plugin kommt nicht von mir und wurde nie wirklich getestet - sorry dafür. Das Plugin wird in der nächsten Version gelöscht und das Resizing wird per Canvas im Browser laufen.

Deswegen kann ich keinen Support für das Plugin liefern.

**Comment by ynamite** [comment]
Kein Problem! Hab den Fehler nur festgestellt und dachte ich melde es.

Aber nicht so wichtig, dann bin ich mal auf die nächste Version gespannt! :)
