### ISSUE TITLE
Uploading Directories At Once With webkitdirectory

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/multiupload#37]
Offenbar ist es jetzt in Frirefox, Edge und Chrome möglich, komplette Verzeichnisse hochzuladen. IMHO eine nützliche Erweiterung.
https://codepen.io/simevidas/pen/ZJjmWG?editors=0010

**Comment by hirbod** [comment]
Japp. Vielen Dank! Langersehntes Feature, das nur Webkit konnte. Steht auf dem Plan!
