### ISSUE TITLE
Doku/README

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/multiupload#4]
Ein paar Infos zum Addon, wie es funktioniert, was man beachten sollte, wie man es als Dev integrieren kann (etwa für yform…), welche Systemvoraussetzungen notwendig sind, usw.

**Comment by AWqxKAWERbXo** [comment]
gerne stichwortartig zusammenschreiben, ich mach dann gerne den Text drum herum.

**Comment by darwin26** [comment]
is hier noch was zu machen. ansonsten close.

**Comment by schuer** [comment]
Ich habe es leider nicht weiter verfolgt, weil ich zu viele andere Themen hatte. Wenn du das Gefühl hast, @darwin26, das die Doku ausreicht, dann schließe gerne.
