### ISSUE TITLE
Ich denke, ich steige mit ein :)

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/multiupload#9]
Schön, das mein AddOn gerettet wurde. Ich denke, ich übernehm das Ding wieder :)
Ich müsste mal hier eingeladen werden. Das aktuelle AddOn ist eh total verschrottet, ich werde es es höchstwahrscheinlich neu aufbauen. (ich meine primär den JS-Part)

**Comment by hirbod** [comment]
Hab auch schon die ersten Probleme mit PHP 7.1 bei mir lokal gefixed. Würd ich im Anschluss auch pushen.

**Comment by schuer** [comment]
Schön, dass du dabei bist, @Hirbod.

Aktueller Project Lead ist @darwin26, ihr müsstet euch dann abstimmen, wie ihr es handhaben wollt. Wenn er weiter Lead bleiben möchte, sollte er sicherlich Vorrang haben. Aber das soll dich ja nicht daran hindern, ganz viel einzubringen. Wir haben alle die gleichen Rechte, nur haben wir uns darauf geeinigt, dem Lead etwas mehr zuzugestehen, siehe Regeln: https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io#regeln

**Comment by schuer** [comment]
@Hirbod: Wäre übrigens prima, wenn du auch in den Slack kämest :)

**Comment by hirbod** [comment]
@schuer danke schon mal für die Einladung.

> Jeder kann in jedem Projekt mitmachen, mitdiskutieren und mitbestimmen. Dabei ist jede Stimme grundsätzlich gleichwertig. Allerdings behalten wir jeder Person, die ein Projekt gestartet oder maßgeblich geprägt hat, ein gewisses Sonderstimmrecht vor.

Da bleibt natürlich die Frage, wer das Projekt gestatet und maßgeblich geprägt hat :). Prinzipiell ist das mein Addon und mein Code. Es wurde für REDAXO 5 geupdated und portiert. Für REDAXO5 hat es @darwin26 sicherlich geprägt. Da ich es unter keiner Lizenz veröffentlicht hatte, hätte man mich prinzipiell fragen müssen. Ich möchte hier aber gar keine Grundsatzdiskussion beginnen. Ich freue mich, dass das jemand übernommen hat und werde erstmal nur ein paar Kleinigkeiten zur PHP 7 Stabilität beitragen. Wenn ich die Zeit gefunden habe, den kompletten JS-Part zu erneuern, würde ich mich mit @darwin26 mal besprechen :)

**Comment by joachimdoerr** [comment]
Hello @Hirbod schön das du wieder dabei bist!

**Comment by hirbod** [comment]
@schuer Thema Slack: ich werde vielleicht demnächst mal reinschauen.

**Comment by darwin26** [comment]
@Hirbod ... na dann hat sich das ja gelohnt, es nach R5 zu murksen  ;) ... jetzt bist du wieder am Ruder. Welcome back... und du darfst gerne es wieder übernehmen. (hab aber damals schon kurz gefragt bei dir ... antwort (?) weiß ich jetzt nicht mehr sorry ...

**Comment by hirbod** [comment]
@darwin26 ich rudere mit :)
find es ja schön, das hier gemeinsam gearbeitet wird. wo gehen PRs aktuell hin? In dein Repo, oder direkt hier rein?

**Comment by darwin26** [comment]
hier ist "mein" letzter stand drin .. (habs dann selber von FOR geforked ... :) )

**Comment by darwin26** [comment]
okay. hab nicht gefragt. war n anderes AddOn wo ich gefragt habe... hier offiziell, sry , und du darfst jede Zeile die ich da reingepackt habe, gerne haben ;) ... next RexDay ist Dir n Getränk Deiner Wahl sicher. Gruß Chris

**Comment by hirbod** [comment]
alles gut. ich stelle das ding jetzt eh unter MIT lizenz.
edit: @schuer hat das schon getan :). Passt so. Erster PR trudelt jetzt ein

**Comment by hirbod** [comment]
Hm, jetzt wurd es wohl gleich commited.
https://github.com/FriendsOfREDAXO/multiupload/commit/aee7a21bc730c4adbb623f0f24268027c538b850

Ich denke aber, die eine Mini-Änderung ist eh egal

**Comment by darwin26** [comment]
jep... Mini... ansonsten hat mir @schuer das erst gestern wieder hingehalten (nett gemeint) ;)
https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io#ein-release-eines-addons-erstellen

**Comment by hirbod** [comment]
Beide Links tot. Aber ich hab sie gelesen. Ab der nächsten Änderungen dann. Regeln sind ja gut, sonst wir es chaotisch.

Kannst du vllt das AddOn bei redaxo.org löschen? Dann würde ich nämlich auch die releases dort pflegen. (benötige den key)

**Comment by darwin26** [comment]
gern . werd ich machen. bin grad unterwegs und vor montag leider nicht... 

mom...
wenn s nur löschen is... sollte nun raus sein...

**Comment by schuer** [comment]
@Hirbod Nachtrag: Damit https://friendsofredaxo.github.io dich als Project Lead listet, müsstest du bitte deine Sichtbarkeit von private auf public ändern auf dieser Seite: https://github.com/orgs/FriendsOfREDAXO/people

**Comment by hirbod** [comment]
@schuer erledigt
